version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    image: trust-review_nginx:development
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/apps
      - ./docker/dev/nginx/logs:/var/log/nginx
    ports:
      # Laravel port
      - 8080:80
    links:
      - php

  # PHP FastCGI Process Manager container
  php:
    image: trust-review_php:development
    build:
      context: docker/dev/php
      dockerfile: Dockerfile
    volumes:
      - ./apps/:/var/www/apps
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=0 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - postgres
      - postgres-testing
      - redis
      - mailhog

  # PostgreSQL database container
  postgres:
    build:
      context: docker/dev/postgres
      dockerfile: Dockerfile
    volumes:
      # Database volume
      - database:/var/lib/postgresql/data
      # Temp volume to allow using dumps
      - ./docker/dev/postgres/dumps/:/tmp/
    ports:
      - 54321:5432
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  adminer:
    image: adnan007/adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_USERNAME=app
      - ADMINER_DEFAULT_PASSWORD=app
      - ADMINER_DEFAULT_DB=app

  # PostgreSQL testing database container
  postgres-testing:
    build:
      context: docker/dev/postgres
      dockerfile: Dockerfile
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  # Redis container
  redis:
    build:
      context: docker/dev/redis
      dockerfile: Dockerfile
    volumes:
      - redis:/data
    ports:
      - 63791:6379

  # Mailhog container (SMTP testing)
  mailhog:
    build:
      context: docker/dev/mailhog
      dockerfile: Dockerfile
    ports:
      - 8026:8025
      
######### Volumes ###################################

volumes:
  database:
    driver: local
  redis:
    driver: local