version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    image: trust-review_nginx:development
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      # Laravel port
      - 8000:80
    links:
      - php

  # PHP FastCGI Process Manager container
  php:
    image: trust-review_php:development
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/src
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=0 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - mysql
      - mailhog

  # MySQL database container
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    volumes:
      # Database volume
      - database:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app

  adminer:
    image: adnan007/adminer
    restart: always
    ports:
      - 8002:8080
    environment:
      - ADMINER_DEFAULT_DRIVER=server
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DEFAULT_USERNAME=app
      - ADMINER_DEFAULT_PASSWORD=app
      - ADMINER_DEFAULT_DB=app

  # Mailhog container (SMTP testing)
  mailhog:
    build:
      context: docker/mailhog
      dockerfile: Dockerfile
    ports:
      - 8003:8025
      
######### Volumes ###################################

volumes:
  database:
    driver: local
    